### ISSUE TITLE
Can you update the test-cors.org website?

### ISSUE THREAD

**Issue by tombrown52** [monsur/test-cors.org#10]

**Comment by monsur** [comment]
Hi Tom. Can you be more specific about what needs updating? I just checked and was able to issue a query on test-cors.org.

**Comment by monsur** [comment]
Ah nevermind, I assume you are referring to https://github.com/monsur/test-cors.org/pull/9? I'll update it. Thanks!

**Comment by monsur** [comment]
Done.
