### ISSUE TITLE
http://test-cors.org/ and https://test-cors.org/ are not working

### ISSUE THREAD

**Issue by ThomasOrlita** [monsur/test-cors.org#18]
The non-www versions of this website are returning 404.

**Comment by monsur** [comment]
Could this have been a transient issue? When I visit test-cors.org, it works (although it redirects to www.test-cors.org). If you are still having issues, can you reopen and share how you reproduced it?

**Comment by ThomasOrlita** [comment]
It works if I open test-cors.org without adding the http(s) protocol. It seems that Chrome automatically redirects it to the correct version.
But if I add http(s):// in front of that (or click the first link in readme), it shows the error.

**Comment by monsur** [comment]
Hi I made some config updates, can you check to see if things are working now (it may also take some time for dns changes to propagate).
